name: Report Release to Telegram

on:
  repository_dispatch:
    types: [trigger-telegram-report]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set builddate
        id: generate-builddate
        run: echo "builddate=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+5 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :

      - name: Fetch Latest Release
        id: fetch_release
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "Using release event data"
            echo "RELEASE_NAME=${{ github.event.release.name }}" >> $GITHUB_ENV
            echo "RELEASE_URL=${{ github.event.release.html_url }}" >> $GITHUB_ENV
            echo "RELEASE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "Fetching latest release data"
            LATEST_RELEASE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest)
            echo "RELEASE_NAME=$(echo $LATEST_RELEASE | jq -r '.name')" >> $GITHUB_ENV
            echo "RELEASE_URL=$(echo $LATEST_RELEASE | jq -r '.html_url')" >> $GITHUB_ENV
            echo "RELEASE_TAG=$(echo $LATEST_RELEASE | jq -r '.tag_name')" >> $GITHUB_ENV
          fi

      - name: Getting KernelSU version
        id: integrate-ksu
        run: |
          if [ -d "./KernelSU" ]; then
            rm -rf "./KernelSU"
          fi

          git clone --recursive -j $(nproc) --branch master https://github.com/backslashxx/KernelSU KernelSU

          KernelSU_VERSION=$(git -C KernelSU describe --abbrev=0 --tags)

          echo "KernelSU version: $KernelSU_VERSION"

          echo "KernelSU_VERSION=$KernelSU_VERSION" >> $GITHUB_ENV

      - name: Getting KernelSU-Next version
        id: integrate-kernelsu-next
        run: |
          if [ -d "./KernelSU-Next" ]; then
            rm -rf "./KernelSU-Next"
          fi

          git clone --recursive -j $(nproc) --branch next https://github.com/KernelSU-Next/KernelSU-Next KernelSU-Next

          KERNELSUN_VERSION=$(git -C KernelSU-Next describe --abbrev=0 --tags)

          echo "KernelSU-Next version: $KERNELSUN_VERSION"

          echo "KERNELSUN_VERSION=$KERNELSUN_VERSION" >> $GITHUB_ENV

      - name: Getting SukiSU-Ultra version
        id: integrate-sukisu-ultra
        run: |
          if [ -d "./KernelSU" ]; then
            rm -rf "./KernelSU"
          fi

          git clone --recursive -j $(nproc) --branch main https://github.com/ShirkNeko/SukiSU-Ultra KernelSU

          SUKISU_VERSION=$(git -C KernelSU describe --abbrev=0 --tags)

          echo "SUKISU version: $SUKISU_VERSION"

          echo "SUKISU_VERSION=$SUKISU_VERSION" >> $GITHUB_ENV

      - name: Report to Telegram
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        if: env.TG_TOKEN != null
        run: |
          TG_CHAT="@cvnertnc"

          MSG="üöÄ *For all Kernels ROOT Version is Updated!* üî•

          ‚ñ´Ô∏è *Kernel:* 4.14.336.Astera
          ‚ñ´Ô∏è *Kernel:* 4.14.355.Power
          ‚ñ´Ô∏è *Kernel:* 4.14.336.Nova

          ‚ñ´Ô∏è *Device:* Begonia
          ‚ñ´Ô∏è *Non-Patch Variant*
          ‚ñ´Ô∏è *KernelSU:* ${{ env.KernelSU_VERSION }}
          ‚ñ´Ô∏è *KernelSU-Next:* ${{ env.KERNELSUN_VERSION }}
          ‚ñ´Ô∏è *SukiSU-Ultra:* ${{ env.SUKISU_VERSION }}
          ‚ñ´Ô∏è *APatch:* Supported
            [Non-patch variants of Power and Nova kernels, except Astera kernel, support APatch.]

          ‚ñ´Ô∏è *SUSFS:* v1.5.8 Supported
          ‚ñ´Ô∏è *KPM:* Supported
            [Power and Nova kernels support KPM except Astera kernel.]
          ‚ñ´Ô∏è *Mountify:* Supported
          ‚ñ´Ô∏è *Release:* ${{ env.RELEASE_NAME }}

          üì• *Download Links:*
          - GitHub Release: [${{ env.RELEASE_NAME }}](${{ env.RELEASE_URL }})
          - KernelSU Manager:
            [Release](https://github.com/backslashxx/KernelSU/releases/${{ env.KernelSU_VERSION }}) | [Nightly](https://nightly.link/backslashxx/KernelSU/workflows/build-manager/master)
          - KernelSU-Next Manager:
            [Release](https://github.com/KernelSU-Next/KernelSU-Next/releases/${{ env.KERNELSUN_VERSION }}) | [Nightly](https://nightly.link/KernelSU-Next/KernelSU-Next/workflows/build-manager-ci/next/Manager)
          - SukiSU-Ultra Manager:
            [Release](https://github.com/ShirkNeko/SukiSU-Ultra/releases/${{ env.SUKISU_VERSION }}) | [Nightly](https://nightly.link/ShirkNeko/SukiSU-Ultra/workflows/build-manager/main)
          - SUSFS Module: 
            [Release](https://github.com/sidex15/susfs4ksu-module/releases/latest) | [Nightly](https://nightly.link/sidex15/susfs4ksu-module/workflows/build/v1.5.2+)
          - Mountify Module: [Release](https://github.com/backslashxx/mountify/releases/latest)

          ‚ö†Ô∏è *Note:* There has been a variant change for KernelSU. If you are using KernelSU and have updated, please delete the manager on your device and download from release or nightly and update your manager.

          ‚ö†Ô∏è *Note:* Regardless of MIUI or AOSP. The best working for my device is Power Kernel. I recommend you to use Power Kernel variants.
          ‚ö†Ô∏è *Note:* Using Astera and Nova kernel is completely your choice. Test it and use the best kernel for your device.
          ‚ö†Ô∏è *Note:* To prevent the risk of your device becoming bootlopped after the kernel installation, please backup your current kernel before flashing the kernel.

          *Please Read:*
          https://t.me/cvnertnc/218

          Astera Kernel by [MrErenK](https://t.me/Mr_ErenK)
          Power Kernel by [Sai Krishna](https://t.me/Saikrishna1504)
          Nova Kernel by [Abdul7852](https://t.me/Abdul7852)
          KernelSU, KernelSU-Next, SukiSU-Ultra and SUSFS patches by [CEHunter ‚öù](https://t.me/the_CEHunter)

          *Follow:* [cvnertnc](https://t.me/cvnertnc)
          *Join:* [cvnertnc-Chat](https://t.me/cvnertnc_chat)
          "

          POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
          curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "disable_web_page_preview=true" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_CHAT}" "$POST"
